INSERT INTO player (name)
VALUES ('Roger Federer'),
       ('Rafael Nadal'),
       ('Novak Djokovic'),
       ('Serena Williams'),
       ('Ashleigh Barty'),
       ('Fedorino Balerino'),
       ('Daniil Medvedev'),
       ('Carlos Alcaraz'),
       ('Iga Świątek'),
       ('Stefanos Tsitsipas'),
       ('Naomi Osaka');

INSERT INTO match (first_player_id, second_player_id, winner_id)
VALUES (1, 2, 1),
       (3, 7, 7),
       (2, 5, 2),
       (10, 1, 10),
       (3, 6, 6),
       (8, 7, 8),
       (1, 4, 4),
       (2, 3, 2),
       (4, 5, 4),
       (6, 7, 7),
       (8, 9, 8),
       (10, 1, 1),
       (3, 11, 3),
       (5, 6, 5),
       (7, 8, 8),
       (9, 10, 9),
       (11, 2, 2),
       (1, 7, 1),
       (4, 8, 4),
       (6, 10, 10),
       (3, 9, 3),
       (5, 11, 11);
